### PR TITLE
User input

### PR DESCRIPTION
**Pull request by hindsjay**
Hi team!
Made the changes to the user inputs to make them controlled components.
In order to fix the little bug where on "play again" the user inputs no longer work I needed to add back in the document.removeEventListener for the keydown events into the componentWillUnmount method.
Also made minor revisions to Maze.js to keep things more consistent (i.e. "e" for event instead of writing out event in full).

Thanks!

### CODE REVIEW

**Comment by mtthdz** [comment]
Looks great.

Thanks

**Comment by cclzhang** [comment]
approved

**Comment by brittgiles** [comment]
So good!!

**Comment by hindsjay** [comment]
Thanks team!

**Pull request merged**
